from io import BytesIO

class DAVProvider:
    _count_get_resource_inst: int
    def is_readonly(self) -> bool: ...
    
class DAVNonCollection:
    path: str
    name: str
    environ: dict
    provider: DAVProvider
    def __init__(self, path: str, environ: dict): ...

    def remove_all_properties(self, *, recursive: bool) -> None: ...
    def remove_all_locks(self, *, recursive: bool) -> None: ...
    
    def get_content_length(self) -> int: ...
    def get_content_type(self) -> str: ...
    def get_creation_date(self) -> int: ...
    def get_display_name(self) -> str: ...
    def get_etag(self) -> str: ...
    def get_last_modified(self) -> int: ...
    def is_link(self) -> bool: ...
    def support_etag(self) -> bool: ...
    def support_ranges(self) -> bool: ...
    def support_recursive_move(self, dest_path: str) -> bool: ...
    
    def move_recursive(self, dest_path: str) -> None: ...
    
    def get_content(self) -> BytesIO: ...
    def begin_write(self, *, content_type: str | None = None) -> BytesIO: ...
    def delete(self) -> None: ...

    def copy_move_single(self, dest_path: str, *, is_move: bool) -> None: ...
    def set_last_modified(self, dest_path: str, time_stamp: str, *, dry_run: bool) -> bool: ...
    
   

class DAVCollection:
    path: str
    name: str
    environ: dict
    provider: DAVProvider
    def __init__(self, path: str, environ: dict) -> None: ...
    
    def remove_all_properties(self, *, recursive: bool) -> None: ...
    def remove_all_locks(self, *, recursive: bool) -> None: ...
    
    
    def get_creation_date(self) -> int: ...
    def get_display_name(self) -> str: ...
    def get_directory_info(self) -> None: ...
    def get_etag(self) -> None: ...
    def get_used_bytes(self) -> int: ...
    def get_available_bytes(self) -> int: ...
    def get_last_modified(self) -> int: ...
    def is_link(self) -> bool: ...
    def support_recursive_move(self, dest_path: str) -> bool: ...
    
    def get_member_names(self) -> list[str]: ...
    def get_member(self, name: str) -> DAVNonCollection | DAVCollection | None: ...

    def create_collection(self, name: str) -> None: ...
    def create_empty_resource(self, name: str) -> DAVNonCollection: ...

    def delete(self) -> None: ...
    def move_recursive(self, dest_path: str) -> None: ...
    def copy_move_single(self, dest_path: str, *, is_move: bool) -> None: ...
    def set_last_modified(self, dest_path: str, time_stamp: str, *, dry_run: bool) -> bool: ...
    